### ISSUE TITLE
Uploading fonts not working at all...

### ISSUE THREAD

**Issue by BinaryBen** [blinksh/fonts#1]
![image](https://cloud.githubusercontent.com/assets/12827556/19916609/a7be2af4-a0f6-11e6-8704-a889a529273b.png)

Validation gone wrong? Trying to upload a .ttf.

Also, is it possible to use "Open in.." Extensions? I use an app called FontManager which allows install of fonts using this method.

EDIT: Nvm, RTFM/PICNIC problem apparently. Could possibly use a link to instructions in the app then?

**Comment by carloscabanero** [comment]
I dropped the link on the gallery, I thought we might still need something more, but wanted to try that. What do you think?

Great idea the Open in... extension, I might create a new one on Blink for that.

**Comment by BinaryBen** [comment]
To me, the "obvious" thing is to expect to be able to install TTF files in the app and do any confit from within the appearance panel. 

Now that I know why it's a CSS file, it makes sense. But some sort of clearer explanation (especially in the error message) would be handy in the app in addition to the link in the GitHub reader file.

**Comment by BinaryBen** [comment]
Maybe try an error message like:

# Incompatible URL Format
Font families are assigned using CSS files. See the gallery for more information on installing your own fonts. 
[OK]

**Comment by carloscabanero** [comment]
That is a great idea! Will do ;)
