### ISSUE TITLE
Installing fonts

### ISSUE THREAD

**Issue by mikheyev** [blinksh/fonts#11]
I am having issues with powerline fonts rendering correctly (get garbage instead on lines in the output), which has been noted previously. One workaround that has been suggested is to use AnyFont to install a font system-wide. I have done so, but blink doesn’t see them. Other applications do, however.

_Originally posted by @jiahao-shen in https://github.com/blinksh/blink/issues/611#issuecomment-438272762_

**Comment by jldeen** [comment]
Bumping this issue because I have the same problem (used AnyFont but blink doesn’t see them, nor do my css downloaded versions of powerline fonts work) - happy to open a new issue if this one is too stale.

**Comment by eruizdechavez** [comment]
Are you by any chance using Fira Code Nerd Font? 

I had the same issue until I figured out the CSS was wrong on this repo (see #23), so I just opened a pull request to fix it and also embed the font (#25).

**Comment by carloscabanero** [comment]
closing here as we rebumped all the fonts a while ago.
