### ISSUE TITLE
 Fira Code Nerd Font is broken

### ISSUE THREAD

**Issue by Puccet** [blinksh/fonts#23]
It seems like this font is broken, if you choose it in the settings it does not work.

**Comment by ionut-maxim** [comment]
Looks like the problem is fixed in https://github.com/blinksh/fonts/pull/22/files but it wasn't merged yet...

**Comment by Puccet** [comment]
Good to know, when it will be available?

**Comment by thegcat** [comment]
This should be fixed by #22 and could probably be closed.
