### ISSUE TITLE
Need some help been trying to load a font and just cannot get it to work.

### ISSUE THREAD

**Issue by rwboyer** [blinksh/fonts#26]
Unless I am completely missing something I cannot figure out why I cannot load custom fonts into blink...

Here's the URL

https://gist.githubusercontent.com/rwboyer/1b3332af16a1cb3bf09e871ccadc1c02/raw/4be19d29871f2d43a0dad58a806d1da0cc8d1ad1/ibm3270

I am literally putting the above url into blink add font where it asks for a url. Tried doing this a few times with various fonts and it NEVER has worked for me. I get a message:

URL error
fonts are loaded using css files see the gallery for examples.

Probably something stupid I am doing, any help would be great.

Thanks

**Comment by pcho** [comment]
It’s missing a file extension, it should be: https://gist.githubusercontent.com/rwboyer/1b3332af16a1cb3bf09e871ccadc1c02/raw/4be19d29871f2d43a0dad58a806d1da0cc8d1ad1/ibm3270.css

**Comment by yury** [comment]
Closing, feel free to reopen if needed.
